name: Get Pull Request Commit Messages

on:
  pull_request:
    types:
      - synchronize

jobs:
  get_commit_messages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Get Commit Messages
        run: |
          # Determine the base and head commit SHAs
          PR_BASE=$(git merge-base origin/main HEAD)
          PR_HEAD=${{ github.sha }}
          
          # Fetch the commit messages between base and head of the pull request
          COMMIT_MESSAGES=$(git log --pretty=%s ${PR_BASE}..${PR_HEAD})
          
          # Print commit messages
          echo "Commit Messages:"
          echo "$COMMIT_MESSAGES"
