name: validate pull request commit message

on:
  pull_request:
    types:
      - synchronize
      - closed

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Check Squashed Commit Message
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          
        run: |
          # Fetch the pull request and checkout the merge commit
          echo $PR_NUMBER
        continue-on-error: false

      - name: Set Status Check
        if: failure()
        run: echo "Invalid squashed commit message" && exit 1
