name: validate-pr-commit-message

on:
  pull_request:
    types:
      - synchronize

jobs:
  get_commit_messages:
    runs-on: ubuntu-latest

    steps:
      - name: Get Commit Messages
        run: |
          # Get the pull request number
          PR_NUMBER=${{ github.event.number }}
          
          # Fetch the commit messages using the GitHub API
          COMMIT_MESSAGES=$(curl -s "https://api.github.com/repos/${{ github.repository }}/pulls/${PR_NUMBER}/commits" | jq -r '.[].commit.message')
          
          # Print commit messages
          echo "Commit Messages:"
          echo "$COMMIT_MESSAGES"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

